# Generated by Django 4.2 on 2023-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipsTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipsTotal", models.FloatField()),
            ],
        ),
    ]
