# Generated by Django 4.2 on 2023-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0002_tipstotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hours",
            field=models.CharField(max_length=4),
        ),
    ]
