# Generated by Django 4.2 on 2023-04-25 02:53

from django.db import migrations
import weeklyTipsCalculator.models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0003_alter_employee_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=weeklyTipsCalculator.models.NameField(max_length=200),
        ),
    ]
