# Generated by Django 4.2 on 2023-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0004_alter_employee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hours",
            field=models.CharField(max_length=6),
        ),
    ]
