# Generated by Django 4.2 on 2023-04-27 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0006_alter_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
