# Generated by Django 4.2 on 2023-04-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0007_employee_timestamp_employee_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
