# Generated by Django 4.2 on 2023-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0009_alter_employee_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
