# Generated by Django 4.2 on 2023-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "weeklyTipsCalculator",
            "0010_alter_employee_timestamp_alter_employee_updated",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
