# Generated by Django 4.2 on 2023-04-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0011_employee_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipsTotal",
        ),
    ]
