# Generated by Django 4.2 on 2023-05-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0012_delete_tipstotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hours",
            field=models.FloatField(max_length=6),
        ),
    ]
