# Generated by Django 4.2 on 2023-05-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0014_tipstotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="percentageOfTips",
            field=models.FloatField(default=0, max_length=6),
        ),
    ]
