# Generated by Django 4.2 on 2023-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0015_employee_percentageoftips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hours",
            field=models.FloatField(default=0, max_length=6),
        ),
    ]
