# Generated by Django 4.2 on 2023-05-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weeklyTipsCalculator", "0016_alter_employee_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tips",
            field=models.FloatField(default=0, max_length=6),
        ),
    ]
